### ISSUE TITLE
release schedule

### ISSUE THREAD

**Issue by dupainaulevain** [edx/frontend-app-profile#26]
Hi!

Out of curiosity, do you plan to provide releases for this repository?

Thanks in advance for your kind reply

**Comment by davidjoy** [comment]
Hi @dupainaulevain,

A release/deployment strategy for this repo and other micro frontends like it is something we're working on, but we don't quite have anything to share yet as it's all still early in process.  This repo, for instance, is still under active development towards its initial release.  As we learn more we'll certainly share.
